name: CI

on:
  push:
    branches:
      - 'master'
      - 'dev'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install
      run: npm ci
        
    - name: Lint
      run: npm run lint
      
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install
      run: npm ci
      
    - name: Build
      run: npm run build:clean
      
    - name: Seed
      run: npm run seed
      
    - name: Test and Coverage
      run: npm run test:coverage
