name: PR Checks

on: pull_request
      
env:
  NODE_VERSION: '14'

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}
        
    - name: Install
      run: npm ci
        
    - name: Lint
      run: npm run lint
        
    - name: Lint Tests
      run: npm run lint:tests
      
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install
      run: npm ci
      
    - name: Build
      run: npm run build
      
  seed:
    name: "Test Seed"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install
      run: npm ci
      
    - name: Init
      run: npm run init
      
    - name: Seed
      run: npx prisma db seed --preview-feature
      
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install
      run: npm ci
      
    - name: Init
      run: npm run init
      
    - name: Test
      run: npm run test
      
  test-e2e:
    name: "Test End to End"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install
      run: npm ci
      
    - name: Init
      run: npm run init
      
    - name: Test End to End Functions
      run: npm run test:e2e
      
  pr-coverage:
    name: "PR Coverage"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install
      run: npm ci
      
    - name: Init
      run: npm run init
      
    - name: Report Coverage
      uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # ! Commented out because it cause issues with the Github Action
      # with:
      #   changes-only: true
